/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/ClientCompanies": {
    get: {
      parameters: {
        query?: {
          Query?: string;
          PageNumber?: number;
          PageSize?: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateClientCompanyCommand"];
          "text/json": components["schemas"]["CreateClientCompanyCommand"];
          "application/*+json": components["schemas"]["CreateClientCompanyCommand"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/ClientCompanies/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateClientCompanyCommand"];
          "text/json": components["schemas"]["UpdateClientCompanyCommand"];
          "application/*+json": components["schemas"]["UpdateClientCompanyCommand"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StringCommandResult"];
            "application/json": components["schemas"]["StringCommandResult"];
            "text/json": components["schemas"]["StringCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["StringCommandResult"];
            "application/json": components["schemas"]["StringCommandResult"];
            "text/json": components["schemas"]["StringCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/Registrars": {
    get: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GetRegistrarListQuery"];
          "text/json": components["schemas"]["GetRegistrarListQuery"];
          "application/*+json": components["schemas"]["GetRegistrarListQuery"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "application/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
            "text/json": components["schemas"]["ClientCompanyViewModelPaginatedListCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/Users": {
    get: {
      parameters: {
        query?: {
          Query?: string;
          PageNumber?: number;
          PageSize?: number;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult"];
            "application/json": components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult"];
            "text/json": components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult"];
            "application/json": components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult"];
            "text/json": components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/Users/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UserProfileViewModelCommandResult"];
            "application/json": components["schemas"]["UserProfileViewModelCommandResult"];
            "text/json": components["schemas"]["UserProfileViewModelCommandResult"];
          };
        };
      };
    };
  };
  "/api/Users/ActivateDeactivateUser/{id}": {
    patch: {
      parameters: {
        query?: {
          isActive?: boolean;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["UserProfileViewModelCommandResult"];
            "application/json": components["schemas"]["UserProfileViewModelCommandResult"];
            "text/json": components["schemas"]["UserProfileViewModelCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["UserProfileViewModelCommandResult"];
            "application/json": components["schemas"]["UserProfileViewModelCommandResult"];
            "text/json": components["schemas"]["UserProfileViewModelCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
  "/api/Users/SuspendReinstateUser/{id}": {
    patch: {
      parameters: {
        query?: {
          isDisabled?: boolean;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["StringCommandResult"];
            "application/json": components["schemas"]["StringCommandResult"];
            "text/json": components["schemas"]["StringCommandResult"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "text/plain": components["schemas"]["StringCommandResult"];
            "application/json": components["schemas"]["StringCommandResult"];
            "text/json": components["schemas"]["StringCommandResult"];
          };
        };
        /** @description Error */
        default: {
          content: {
            "text/plain": components["schemas"]["ProblemDetails"];
            "application/json": components["schemas"]["ProblemDetails"];
            "text/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ApplicationProfileUserProfileViewModelPaginatedListViewModel: {
      items?: components["schemas"]["UserProfileViewModel"][] | null;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      totalCount?: number;
      hasPreviousPage?: boolean;
      hasNextPage?: boolean;
    };
    ApplicationProfileUserProfileViewModelPaginatedListViewModelCommandResult: {
      /** Format: date-time */
      timeStamp?: string;
      errorFlag?: boolean;
      payload?: components["schemas"]["ApplicationProfileUserProfileViewModelPaginatedListViewModel"];
      message?: string | null;
      /** Format: int32 */
      statusCode?: number | null;
      detail?: string | null;
      instance?: string | null;
      validationErrors?: components["schemas"]["ModelValidationError"][] | null;
    };
    AssetPrice: {
      /** Format: double */
      price?: number;
      /** Format: date-time */
      timestamp?: string;
    };
    ClientCompanyViewModel: {
      id: string;
      description?: string | null;
      isActive?: boolean;
      /** Format: date-time */
      dateCreated?: string | null;
      /** Format: date-time */
      dateUpdated?: string | null;
      name?: string | null;
      code?: string | null;
      registrarId?: string | null;
      /** Format: double */
      currentPrice?: number;
      prices?: components["schemas"]["AssetPrice"][] | null;
    };
    ClientCompanyViewModelCommandResult: {
      /** Format: date-time */
      timeStamp?: string;
      errorFlag?: boolean;
      payload?: components["schemas"]["ClientCompanyViewModel"];
      message?: string | null;
      /** Format: int32 */
      statusCode?: number | null;
      detail?: string | null;
      instance?: string | null;
      validationErrors?: components["schemas"]["ModelValidationError"][] | null;
    };
    ClientCompanyViewModelPaginatedList: {
      items?: components["schemas"]["ClientCompanyViewModel"][] | null;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      totalPages?: number;
      /** Format: int32 */
      totalCount?: number;
      hasPreviousPage?: boolean;
      hasNextPage?: boolean;
    };
    ClientCompanyViewModelPaginatedListCommandResult: {
      /** Format: date-time */
      timeStamp?: string;
      errorFlag?: boolean;
      payload?: components["schemas"]["ClientCompanyViewModelPaginatedList"];
      message?: string | null;
      /** Format: int32 */
      statusCode?: number | null;
      detail?: string | null;
      instance?: string | null;
      validationErrors?: components["schemas"]["ModelValidationError"][] | null;
    };
    CreateClientCompanyCommand: {
      description?: string | null;
      isActive?: boolean;
      fullText?: string | null;
      tags?: string | null;
      caption?: string | null;
      name?: string | null;
      code?: string | null;
      registrarId?: string | null;
    };
    GetRegistrarListQuery: {
      query?: string | null;
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
    };
    ModelValidationError: {
      entity?: string | null;
      field?: string | null;
      type?: string | null;
      value?: Record<string, unknown> | null;
      rawValue?: Record<string, unknown> | null;
      error?: string | null;
      code?: string | null;
      description?: string | null;
    };
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
      [key: string]: unknown;
    };
    StringCommandResult: {
      /** Format: date-time */
      timeStamp?: string;
      errorFlag?: boolean;
      payload?: string | null;
      message?: string | null;
      /** Format: int32 */
      statusCode?: number | null;
      detail?: string | null;
      instance?: string | null;
      validationErrors?: components["schemas"]["ModelValidationError"][] | null;
    };
    UpdateClientCompanyCommand: {
      id: string;
      description?: string | null;
      isActive?: boolean;
      /** Format: uuid */
      rowVersion?: string;
      fullText?: string | null;
      tags?: string | null;
      caption?: string | null;
      name?: string | null;
      code?: string | null;
      registrarId?: string | null;
    };
    UserProfileViewModel: {
      id: string;
      description?: string | null;
      isActive?: boolean;
      /** Format: date-time */
      dateCreated?: string | null;
      /** Format: date-time */
      dateUpdated?: string | null;
      userId?: string | null;
      name?: string | null;
      phoneNumber?: string | null;
      email?: string | null;
      address?: string | null;
      bvn?: string | null;
      dateOfBirth?: string | null;
      isOrganisation?: boolean;
      rcNumber?: string | null;
      tin?: string | null;
      state?: string | null;
      isDisabled?: boolean;
    };
    UserProfileViewModelCommandResult: {
      /** Format: date-time */
      timeStamp?: string;
      errorFlag?: boolean;
      payload?: components["schemas"]["UserProfileViewModel"];
      message?: string | null;
      /** Format: int32 */
      statusCode?: number | null;
      detail?: string | null;
      instance?: string | null;
      validationErrors?: components["schemas"]["ModelValidationError"][] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
